#Einzelne Einträge durch Komma (",") trennen

#vertrauenswürdige IP-Adressen
untrusted_read.trusted_ips=128.55.12.10,10.0.0.1

#Shell-Pfade
shell_exec.shell_paths=/bin/bash,/bin/sh,/bin/dash,/bin/zsh,cmd.exe,powershell.exe

#Log-Pfade
clear_logs.log_paths=/var/log/,/usr/log/,/var/adm/,/var/run/

#Kritische Commands
sensitive_command.sensitive_commands=whoami,hostname,ifconfig,netstat,uname,id,ps,w,who,last,find,locate

#Commands up Rechte zu erhöhen
switch_su.superuser_tools=doas,sudo,elevate,su